# --------------------- Названия объектов ---------------------
INFO_OBJECT_GRASS = "Трава"
INFO_OBJECT_MEAT = "Мясо"
INFO_OBJECT_FRUIT = "Фрукт"
INFO_OBJECT_SPIKE = "Шипы"
INFO_OBJECT_WATER = "Вода"
INFO_OBJECT_BUSH = "Куст"
INFO_OBJECT_TREE = "Дерево"
INFO_OBJECT_STONE = "Камень"
INFO_OBJECT_ROAD = "Дорога"
INFO_OBJECT_ROAD_CROSSING = "Перекрёсток"
INFO_OBJECT_WALL = "Стена"
INFO_OBJECT_FENCE = "Забор"

# --------------------- Ландшафт ---------------------
INFO_BTN_LANDSCAPE = "Ландшафт"
INFO_BTN_WALL = "Стена"
INFO_BTN_FENCE = "Забор"
INFO_BTN_BIOME_PLAINS = "Равнина"
INFO_BTN_BIOME_DESERT = "Пустыня"
INFO_BTN_BIOME_RIVER = "Река"
INFO_BTN_BIOME_SEA = "Море"
INFO_BTN_NATURE = "Природа"
INFO_BTN_TREE = "Дерево"
INFO_BTN_STONE = "Камень"

# --------------------- Интерфейсные надписи (кнопки, меню) ---------------------
INFO_BTN_GAME = "Игра"
INFO_BTN_LIFES = "Расы"
INFO_BTN_ANIMALS = "Животные"
INFO_BTN_OBJECTS = "Объект"
INFO_BTN_PLAYER = "Игрок"
INFO_BTN_CREATE_WORLD = "Создать"
INFO_BTN_LOAD_WORLD = "Загрузить"
INFO_BTN_SAVE_WORLD = "Сохранить"
INFO_BTN_PAUSE = "Пауза"
INFO_BTN_EXIT = "Выйти"
INFO_BTN_RESUME = "Продолжить"
INFO_BTN_CREATE = "Создать"
INFO_INFO_ANIMAL_MEAT = "Мясо: {count}"
INFO_INFO_RESOURCE_AMOUNT = "Количество: {count}"
INFO_BTN_GRASS = "Трава"
INFO_BTN_MEAT = "Мясо"
INFO_BTN_FRUIT = "Фрукт"
INFO_BTN_SPIKE = "Шипы"
INFO_BTN_WATER = "Вода"
INFO_BTN_BUSH = "Куст"
INFO_BTN_PET = "Гладить"
INFO_BTN_HIT = "Ударить"
INFO_BTN_GRAB = "Схватить"
INFO_BTN_DRAW_ROAD = "Дорога"
INFO_BTN_BACK = "Назад"
INFO_BTN_SETTINGS = "Настройки"
INFO_SETTINGS_TITLE = "Настройки"
INFO_SETTINGS_TAB_DISPLAY = "Отображение"
INFO_SETTINGS_SHOW_NAMES = "Показать имена существ"
INFO_SETTINGS_SHOW_STATUS_RINGS = "Показать цветные кольца вокруг существ"
INFO_SETTINGS_MINIMAP_FRUITS = "Показать фрукты на мини-карте"
INFO_SETTINGS_MINIMAP_BUSHES = "Показать кусты на мини-карте"
INFO_SETTINGS_MINIMAP_SPIKES = "Показать шипы на мини-карте"
INFO_SETTINGS_MINIMAP_WATER = "Показать водоёмы на мини-карте"
INFO_SETTINGS_MINIMAP_TREES = "Показать деревья на мини-карте"
INFO_SETTINGS_MINIMAP_STONES = "Показать камни на мини-карте"
INFO_SETTINGS_MINIMAP_ROADS = "Показать дороги на мини-карте"
INFO_BTN_SETTINGS_SAVE = "Сохранить"

# --------------------- Подсказки и сообщения ---------------------
INFO_PLACEMENT_HINT = "ЛКМ — разместить"
INFO_TOOL_PET_HINT = "ЛКМ по существу — погладить"
INFO_TOOL_HIT_HINT = "ЛКМ по существу — ударить"
INFO_TOOL_GRAB_HINT = "ЛКМ по существу — схватить, ЛКМ ещё раз — отпустить"
INFO_TOOL_ROAD_HINT = "Зажмите и ведите ЛКМ — рисовать дорогу"
INFO_TOOL_BIOME_HINT = "Зажмите и ведите ЛКМ — рисовать биом"
INFO_TOOL_WALL_HINT = "Зажмите и ведите ЛКМ — рисовать стену"
INFO_TOOL_FENCE_HINT = "Зажмите и ведите ЛКМ — рисовать забор"
INFO_TOOL_GRAB_RELEASE_HINT = "ЛКМ — отпустить существо"
INFO_TOOL_GRAB_OBJECT_HINT = "ЛКМ — опустить объект"
INFO_EMPTY_STATE_HINT = "Создайте или Откройте мир"
INFO_PAUSE_OVERLAY = "ПАУЗА"
INFO_WORLD_NAME_TEMPLATE = "Мир: {world_name}"
INFO_BRUSH_RADIUS = "Радиус кисти: {radius}"

# --------------------- Диалоги и ошибки ---------------------
INFO_DIALOG_CREATE_TITLE = "Создать мир"
INFO_DIALOG_CREATE_PROMPT = "Введите имя мира:"
INFO_DIALOG_LOAD_TITLE = "Загрузить мир"
INFO_ERROR_TITLE = "Ошибка"
INFO_ERROR_INVALID_WORLD = "Выбранная папка не является миром Simple_Lifes. Нужно расширение {ext} и файл {meta} внутри."

# --------------------- Панель информации ---------------------
INFO_INFO_CREATED = "Создан: {created}"
INFO_INFO_TREE_WOOD = "Древесины: {count}"
INFO_INFO_STONE_AMOUNT = "Камня: {count}"
INFO_INFO_WATER_CHARGES = "Заряды воды: {count}"
INFO_INFO_FOOD_AMOUNT = "Пищи: {count}"
INFO_INFO_DELETE_HINT = "Ctrl+ЛКМ / Del — удалить"

# --------------------- Экраны создания/загрузки мира ---------------------
INFO_WS_SCREEN_TITLE = "Создание мира"
INFO_WS_TITLE_NAME = "Название мира:"
INFO_WS_TITLE_SIZE = "Размер мира:"
INFO_WS_LENGTH = "Длина:"
INFO_WS_WIDTH = "Ширина:"
INFO_WS_NAME_PLACEHOLDER = "Введите имя..."
INFO_WS_SIZE_PLACEHOLDER = "число"
INFO_BTN_WS_CREATE = "Создать"
INFO_WS_ERROR_EMPTY_NAME = "Введите название мира"
INFO_WS_TITLE_SEED = "Сид мира:"
INFO_WS_SEED_PLACEHOLDER = "случайный"
INFO_LW_INFO_SEED = "Сид: {seed}"
INFO_WS_ERROR_SIZE = "Размер должен быть числом от {min} до {max}"

INFO_LW_SCREEN_TITLE = "Загрузка мира"
INFO_LW_EMPTY_LIST = "Миры не найдены"
INFO_LW_INFO_NAME = "Название: {name}"
INFO_LW_INFO_CREATED = "Создан: {created}"
INFO_LW_INFO_SIZE = "Размер: {w} x {h}"
INFO_LW_INFO_CREATURES = "Существ: {count}"
INFO_LW_INFO_FRUITS = "Фруктов: {count}"
INFO_LW_INFO_SPIKES = "Шипов: {count}"
INFO_LW_INFO_WATER = "Водоёмов: {count}"
INFO_LW_INFO_BUSHES = "Кустов: {count}"
INFO_LW_INFO_CAMPFIRES = "Костров: {count}"
INFO_LW_INFO_ROADS = "Дорог: {count}"
INFO_BTN_LW_LOAD = "Загрузить"
INFO_BTN_LW_DELETE = "Удалить"
INFO_LW_CONFIRM_DELETE = "Точно? Ещё раз для удаления"
INFO_LW_SELECT_HINT = "Выберите мир слева"

# --------------------- Диета (общее понятие, расы лишь выбирают значение) ---------------------
INFO_INFO_DIET = "Диета: {diet}"
INFO_DIET_HERBIVORE = "Травоядное"
INFO_DIET_CARNIVORE = "Плотоядное"
INFO_DIET_OMNIVORE = "Всеядное"