"""Настройки, специфичные для расы 'Круг'."""
from settings import WATER_PUDDLE_CHARGE_VALUE
from ...all_needed.diet import DIET_HERBIVORE, FOOD_CATEGORY_PLANT

RACE_DIET = DIET_HERBIVORE
RACE_FOOD_CATEGORY_MAP = {
    "fruit": FOOD_CATEGORY_PLANT,
}

# ---------- Базовые параметры существ ----------
HP_MAX = 100
HUNGER_MAX = 25
THIRST_MAX = 25
SPEED = 120
EAT_DISTANCE = 20
SPIKE_DAMAGE = 12
SPIKE_INVULN_DURATION = 0.6
FRUIT_HP_BONUS = 2
FRUIT_HUNGER_BONUS = 5
WATER_DRINK_RATE = 3.0
CHILD_CREATURE_RADIUS = 7
VISION_RADIUS = 900

# ---------- Черты характера ----------
TEMPERAMENT_NORMAL = "Обычный"
TEMPERAMENT_EXPLORER = "Исследователь"
TEMPERAMENT_LAZY = "Ленивец"
TEMPERAMENT_LIST = [TEMPERAMENT_NORMAL, TEMPERAMENT_EXPLORER, TEMPERAMENT_LAZY]

SPEED_MULTIPLIER = {
    TEMPERAMENT_NORMAL: 1.0,
    TEMPERAMENT_EXPLORER: 1.1,
    TEMPERAMENT_LAZY: 0.65,
}

EXPLORE_DISTANCE = {
    TEMPERAMENT_NORMAL: (80, 200),
    TEMPERAMENT_EXPLORER: (250, 600),
    TEMPERAMENT_LAZY: (30, 90),
}

EXPLORE_TIMER = {
    TEMPERAMENT_NORMAL: (2.5, 5.0),
    TEMPERAMENT_EXPLORER: (1.2, 2.5),
    TEMPERAMENT_LAZY: (5.0, 9.0),
}

LAZY_COMFORT_RADIUS = 140
LAZY_RISK_REACTION_DISTANCE = 75
DEFAULT_RISK_REACTION_DISTANCE = 45

AVOID_MARGIN = 15

STUCK_CHECK_INTERVAL = 1.0
STUCK_DISTANCE_THRESHOLD = 15

MAX_PLAYER_MEMORY = 50

# ---------- Пол ----------
GENDER_MALE = "male"
GENDER_FEMALE = "female"
GENDER_LIST = [GENDER_MALE, GENDER_FEMALE]

CREATURE_COLOR_MALE = (200, 30, 30)
CREATURE_COLOR_MALE_DEAD = (90, 15, 15)
CREATURE_COLOR_FEMALE = (230, 100, 180)
CREATURE_COLOR_FEMALE_DEAD = (110, 45, 85)

# ---------- Эмпатия/помощь сородичам ----------
HELP_APPROACH_DISTANCE = 70
SOCIAL_REQUEST_HOLD_TIME = 2.5
HELP_COMMIT_MIN_DURATION = 3.0

# ---------- Отношения между существами ----------
RELATIONSHIP_TALK_RATE = 3.0
RELATIONSHIP_HELP_BONUS_HELPED = 6.0
RELATIONSHIP_HELP_BONUS_HELPER = 2.0
EMPATHY_MIN_RELATIONSHIP = -30
RELATIONSHIP_COMPANION_WEIGHT = 3.0
GENDER_OPPOSITE_TALK_BONUS = 1.15
CLOSE_FRIEND_SANITY_RELATIONSHIP = 50.0

# ---------- Заморозка ----------
FREEZE_CHANCE = {
    TEMPERAMENT_NORMAL: 0.25,
    TEMPERAMENT_EXPLORER: 0.10,
    TEMPERAMENT_LAZY: 0.50,
}
FREEZE_DURATION = {
    TEMPERAMENT_NORMAL: (3.0, 7.0),
    TEMPERAMENT_EXPLORER: (1.5, 3.0),
    TEMPERAMENT_LAZY: (6.0, 14.0),
}

STUCK_ESCALATION_THRESHOLD = 3
STUCK_ESCAPE_DISTANCE = (150, 300)

# ---------- Любопытство ----------
CURIOSITY_RANGE = {
    TEMPERAMENT_NORMAL: (0.35, 0.65),
    TEMPERAMENT_EXPLORER: (0.65, 1.0),
    TEMPERAMENT_LAZY: (0.10, 0.35),
}
CURIOSITY_HAZARD_STUDY_DISTANCE = 90
CURIOSITY_DISCOVERY_CHANCE = {
    TEMPERAMENT_NORMAL: 0.30,
    TEMPERAMENT_EXPLORER: 0.75,
    TEMPERAMENT_LAZY: 0.15,
}

# ---------- Энергия / Сон ----------
ENERGY_MAX = 100
ENERGY_DRAIN_INTERVAL = 3.0
ENERGY_LOW_THRESHOLD = 25
ENERGY_SLEEP_RESTORE_RATE = 2.0
ENERGY_FORCED_SLEEP_RESTORE_RATE = 1.0
WAKE_ENERGY_THRESHOLD = {
    TEMPERAMENT_NORMAL: (85, 90),
    TEMPERAMENT_EXPLORER: (80, 85),
    TEMPERAMENT_LAZY: (90, 95),
}

STATE_CALM = "Спокойствие"
STATE_SEEKING = "Занят"
STATE_PANIC = "Паника"
STATE_SLEEP = "Сон"

# ---------- Взаимодействия игрока с существом ----------
PLAYER_PET_SANITY_BONUS = 15
PLAYER_PET_RELATIONSHIP = 10
PLAYER_HIT_DAMAGE = 15
PLAYER_HIT_RELATIONSHIP = -20
PLAYER_GRAB_GOOD_RELATIONSHIP = 5
PLAYER_GRAB_BAD_RELATIONSHIP = -10
PLAYER_CALM_DURATION = 6.0
PLAYER_FEAR_DURATION = 4.0
STAT_ADJUST_STEP_FACTOR = 0.10
STAT_ADJUST_RELATIONSHIP_GOOD = 4
STAT_ADJUST_RELATIONSHIP_BAD = -8

NAME_ASSIGN_RELATIONSHIP_BONUS = 8
NAMED_SANITY_DECAY_MULTIPLIER = 1.25

# ---------- Обмен информацией ----------
SHARE_INFO_INTERVAL = (4.0, 8.0)
SHARE_RESOURCE_MIN_RELATIONSHIP = -10
SHARE_IMPORTANCE_FACTOR = 0.85

# ---------- Поведение существа на нарисованных дорогах ----------
ROAD_FOLLOW_CHANCE_FACTOR = 0.5
ROAD_FOLLOW_REROLL_INTERVAL = (3.0, 6.0)
ROAD_OUTCOME_RADIUS = 90
ROAD_DANGEROUS_THRESHOLD = 2
ROAD_LINK_RESOURCE_MAP = {"water": "water", "bush": "food"}
CROSSING_POINT_TOLERANCE = 10       # px - с какого расстояния до точки перекрёстка существо считается "стоящим" на нём
CROSSING_SWITCH_CHANCE_FACTOR = 0.4

# ---------- Возраст / жизненный цикл ----------
AGE_CHILD_END = 600.0
AGE_YOUNG_ADULT_END = 2100.0
LIFE_STAGE_CHILD = "Ребёнок"
LIFE_STAGE_ADULT = "Взрослый"
LIFE_STAGE_OLD = "Старик"
AGE_NATURAL_DEATH_START = 1800.0
AGE_NATURAL_DEATH_MAX = 3120.0
AGE_NATURAL_DEATH_CHANCE_PER_SEC = 0.0002

OLD_SPEED_MULTIPLIER = 0.7
OLD_ENERGY_DRAIN_MULTIPLIER = 0.6
OLD_MEMORY_DECAY_MULTIPLIER = 1.6
OLD_VISION_RADIUS_MULTIPLIER = 0.75
OLD_SANITY_AURA_RADIUS = 200
OLD_SANITY_AURA_RATE_NEAR = 0.09
OLD_SANITY_AURA_RATE_FAR = 0.02

# ---------- Метаболизм ----------
BASE_HUNGER_INTERVAL = 30.0
BASE_THIRST_INTERVAL = 10.0
HEALING_HUNGER_INTERVAL = 6.0
HEALING_THIRST_INTERVAL = 6.0
STARVING_HUNGER_INTERVAL = 15.0
STARVING_THIRST_INTERVAL = 8.0

METABOLISM_LIFE_STAGE_MULTIPLIER = {
    LIFE_STAGE_CHILD: 1.25,
    LIFE_STAGE_ADULT: 1.0,
    LIFE_STAGE_OLD: 0.85,
}
METABOLISM_TEMPERAMENT_MULTIPLIER = {
    TEMPERAMENT_NORMAL: 1.0,
    TEMPERAMENT_EXPLORER: 1.15,
    TEMPERAMENT_LAZY: 0.85,
}
METABOLISM_STATE_MULTIPLIER = {
    STATE_CALM: 0.9,
    STATE_SEEKING: 1.15,
    STATE_PANIC: 1.6,
    STATE_SLEEP: 0.55,
}
PREGNANCY_METABOLISM_MULTIPLIER = 1.35

ENERGY_TEMPERAMENT_MULTIPLIER = {
    TEMPERAMENT_NORMAL: 1.0,
    TEMPERAMENT_EXPLORER: 1.2,
    TEMPERAMENT_LAZY: 0.75,
}
ENERGY_STATE_MULTIPLIER = {
    STATE_CALM: 0.75,
    STATE_SEEKING: 1.1,
    STATE_PANIC: 1.9,
    STATE_SLEEP: 1.0,
}
PREGNANCY_ENERGY_MULTIPLIER = 1.15

SANITY_STATE_DECAY_MULTIPLIER = {
    STATE_CALM: 0.85,
    STATE_SEEKING: 1.0,
    STATE_PANIC: 1.6,
    STATE_SLEEP: 0.4,
}

WATER_DRINK_DEFICIT_FLOOR = 0.2

GIFT_MIN_RELATIONSHIP = 40.0
GIFT_CHECK_CHANCE = 0.15
FAMILY_FEED_RELATIONSHIP_BONUS_ADULT = 6.0

# ---------- Поведение детей ----------
CHILD_DISTRESS_THRESHOLD = 60.0
CHILD_PLAY_CHANCE = 0.4
CHILD_PLAY_CHECK_INTERVAL = (2.0, 4.0)
CHILD_ROAD_RUN_CHANCE = 0.6
CHILD_EXPLORE_DISTANCE = (30, 90)
CHILD_URGENT_SIGNAL_HOLD_TIME = 14.0
CHILD_PLAY_MAX_DURATION = 12.0
CHILD_TAG_DISTANCE = 25
CHILD_FLEE_DISTANCE = 120

# ---------- Семья и размножение ----------
FAMILY_MIN_RELATIONSHIP = 55.0
FAMILY_PAIR_CHECK_INTERVAL = (4.0, 8.0)
FAMILY_MIN_WELLBEING = 0.7
FAMILY_BOND_DISTANCE = 250
FAMILY_PAIR_BOND_BONUS = 10.0

PREGNANCY_CHANCE_PER_SEC = 0.12
PREGNANCY_DURATION = (75.0, 110.0)
PREGNANCY_SPEED_MULTIPLIER = 0.85
PREGNANCY_MIN_WELLBEING_TO_CARRY = 0.5

FAMILY_CHILD_SPAWN_OFFSET = 25
FAMILY_COOLDOWN_AFTER_BIRTH = 60.0
FAMILY_PARENT_START_RELATIONSHIP = 60.0
FAMILY_TEMPERAMENT_INHERIT_CHANCE = 0.5

FAMILY_REUNITE_EXIT_DISTANCE = 130
FAMILY_REUNITE_MIN_DURATION = 3.0
PARTNER_REUNITE_TRIGGER_DISTANCE = 400
PARTNER_REUNITE_COOLDOWN = (25.0, 45.0)

CHILD_FEED_HUNGER_THRESHOLD = 12.0
CHILD_FEED_THIRST_THRESHOLD = 12.0
PARENT_FEED_CHECK_INTERVAL = (3.0, 6.0)
PARENT_FEED_MIN_WELLBEING = 0.55
PARENT_CARRY_WATER_HYDRATION = WATER_PUDDLE_CHARGE_VALUE
FEED_DISTANCE = EAT_DISTANCE
FAMILY_FEED_RELATIONSHIP_BONUS = 4.0

ELDER_WARD_CHECK_INTERVAL = (3.0, 6.0)
ELDER_WARD_ENERGY_DRAIN_RATE = 0.4
ELDER_ROAD_FOLLOW_DAMPENER = 0.5

# ---------- Конфликты ----------
RESOURCE_COMPETE_RADIUS = 60
RESOURCE_STEAL_PENALTY = -8.0
RESOURCE_STEAL_MIN_HUNGER_URGENCY = 15.0
JEALOUSY_CHECK_DISTANCE = 400
JEALOUSY_PENALTY_PARTNER = -3.0
JEALOUSY_PENALTY_RIVAL = -5.0
JEALOUSY_OPPOSITE_GENDER_ONLY = True
JEALOUSY_CHANCE_PER_SEC = 0.08
QUARREL_THRESHOLD = -25.0
QUARREL_CHANCE_PER_SEC = 0.05
QUARREL_PENALTY = -4.0

# ---------- Гормональный бум ----------
PUBERTY_TRIGGER_AGE_MIN = 600.0
PUBERTY_TRIGGER_AGE_MAX = 1020.0
PUBERTY_DURATION_RANGE = (120.0, 420.0)
PUBERTY_COURTSHIP_RECHECK_INTERVAL = (2.0, 4.0)
PUBERTY_WELLBEING_DISCOUNT = 0.10
PUBERTY_PREGNANCY_CHANCE_MULTIPLIER = 4.0
PUBERTY_SPEED_BONUS_RANGE = (0.15, 0.30)
PUBERTY_CURIOSITY_RANGE = (0.7, 1.0)
PUBERTY_QUARREL_CHANCE_MULTIPLIER = 2.5
PUBERTY_TALK_RATE_MULTIPLIER = 1.6
PUBERTY_PAIR_RELATIONSHIP_DISCOUNT = 15.0
PUBERTY_SANITY_DECAY_MULTIPLIER = 1.4
PUBERTY_RING_COLOR = (200, 80, 220)

# ---------- Территория самцов ----------
TERRITORY_ENABLED_GENDER = GENDER_MALE
TERRITORY_CLAIM_TIME = 8.0
TERRITORY_MAX_CLAIMS_PER_TYPE = 2
TERRITORY_BUSH_CLAIM_RADIUS = 45
TERRITORY_INTRUSION_RADIUS = 70
TERRITORY_GUARD_APPROACH_DISTANCE = 55
TERRITORY_INTRUDER_PENALTY = -15.0
TERRITORY_CONFRONT_COOLDOWN = (6.0, 12.0)
TERRITORY_EXEMPT_ALL_CHILDREN = False
TERRITORY_PURSUIT_COMMIT_TIME = 3.0
TERRITORY_PURSUIT_EXIT_RADIUS_FACTOR = 1.6
TERRITORY_CONFRONT_FEAR_DURATION = 3.0
TERRITORY_PUBLIC_DOMAIN_RADIUS = 500.0

# ---------- Поведение вокруг склада (не сам объект — см. settings.py) ----------
STORAGE_BUILD_OFFSET_RANGE = (80, 220)
STORAGE_SUPPLY_CHECK_INTERVAL = (4.0, 7.0)
STORAGE_CONSUME_HUNGER_THRESHOLD = CHILD_FEED_HUNGER_THRESHOLD
STORAGE_CONSUME_THIRST_THRESHOLD = CHILD_FEED_THIRST_THRESHOLD
STORAGE_FIELD_WATER_HYDRATION = PARENT_CARRY_WATER_HYDRATION

# ---------- Труп / кладбище (поведение, не сам объект) ----------
GRAVEYARD_ALERT_HOLD_TIME = 25.0
CORPSE_APPROACH_DISTANCE = 22
CORPSE_DRAG_SPEED_FACTOR = 0.55
GRAVEYARD_BUILD_OFFSET_RANGE = (450, 750)
GRAVEYARD_CAMPFIRE_LINK_RADIUS = 1000.0

LANDMARK_REGISTER_INTERVAL = (1.0, 2.0)

# ---------- Сон у костра ----------
SLEEP_SPOT_MIN_DISTANCE = 15
SLEEP_SPOT_MAX_RADIUS_FACTOR = 0.5
SLEEP_SPOT_ARRIVAL_DISTANCE = 14

# ---------- Паника ----------
PANIC_SPEED_MULTIPLIER = 1.35
PANIC_SCAN_DISTANCE = 90

# ---------- Активный поиск ----------
ACTIVE_SEARCH_DISTANCE = (150, 350)
ACTIVE_SEARCH_TIMER = (1.0, 2.0)

CORPSE_LIFETIME = 30.0

# ---------- Насыщение потребностей / сознание ----------
HUNGER_SATISFY_THRESHOLD = 20.0
THIRST_SATISFY_THRESHOLD = 20.0
SANITY_SATISFY_THRESHOLD = 80.0

SANITY_MAX = 100
SANITY_DECAY_INTERVAL = 6.0
SANITY_LOW_THRESHOLD = 50
SANITY_PANIC_THRESHOLD = 25
SANITY_CAMPFIRE_RESTORE_RATE_NEAR = 0.2
SANITY_CAMPFIRE_RESTORE_RATE_FAR = 0.06
SANITY_TALK_RATE = {
    TEMPERAMENT_NORMAL: 0.25,
    TEMPERAMENT_EXPLORER: 0.5,
    TEMPERAMENT_LAZY: 0.08,
}
TALK_DISTANCE = 45

# ---------- Добыча ресурсов и стройка (поведение) ----------
CREATURE_CARRY_CAPACITY_RANGE = (4, 10)
GATHER_APPROACH_DISTANCE = 20
CONSTRUCTION_APPROACH_DISTANCE = 20
CONSTRUCTION_CHECK_INTERVAL = (5.0, 10.0)
CONSTRUCTION_SITE_SEARCH_RADIUS = 250
CAMPFIRE_BUILD_OFFSET_RANGE = (60, 160)
RESOURCE_GATHER_RATE = 1.0

BUILD_HELP_MIN_RELATIONSHIP = 25.0
BUILD_HELP_JOIN_CHANCE = 0.15
BUILD_HELP_CHECK_INTERVAL = (3.0, 6.0)
BUILD_HELP_RELATIONSHIP_BONUS = 12.0
BUILD_HELP_SPEED_BONUS_PER_HELPER = 0.6
CONSTRUCTION_CLEARANCE_MARGIN = 15
ORPHAN_SITE_SEARCH_RADIUS_FACTOR = 2.5

# ---------- Детские дороги ----------
CHILD_ROAD_COLOR_PENDING = (255, 230, 40)
CHILD_ROAD_COLOR_SAFE = (80, 180, 255)
CHILD_ROAD_COLOR_DANGEROUS = (230, 30, 30)
CHILD_ROAD_SAFETY_CHECK_RADIUS = 90
CHILD_ROAD_VERIFY_CHECK_INTERVAL = (3.0, 6.0)
CHILD_ROAD_PLAY_COOLDOWN = (4.0, 9.0)
PSYCHE_CHILD_ROAD_PLAY_RATE = 0.45
CHILD_ROAD_DANGER_FEAR_DURATION = 5.0
CHILD_ROAD_DISINTEREST_THRESHOLD = 3
CHILD_ROAD_DISINTEREST_DURATION = 100.0

# ---------- Семейный склад запасов (сам объект, поведение вокруг него - выше) ----------
STORAGE_FIELD_RADIUS = 22
STORAGE_FIELD_MAX_FRUITS = 12
STORAGE_FIELD_MAX_WATER = 12
STORAGE_FIELD_COLOR_BORDER = (120, 80, 40)
STORAGE_FIELD_DEPOSIT_DISTANCE = STORAGE_FIELD_RADIUS + 10

# ---------- Кладбище (сам объект) ----------
GRAVEYARD_DEFAULT_SIZE = (140, 100)
GRAVEYARD_COLOR_FILL = (90, 60, 40)
GRAVEYARD_COLOR_BORDER = (150, 150, 150)
GRAVEYARD_BORDER_THICKNESS = 6
GRAVEYARD_DATA_RETENTION = 900.0
GRAVEYARD_BURIAL_DISTANCE = 70

# ---------- Требования построек: {ресурс: количество} + время стройки (сек) ----------
BUILDING_REQUIREMENTS = {
    "campfire": {"wood": 2, "stone": 1, "build_time": 3.0},
    "storage": {"wood": 15, "stone": 12, "build_time": 15.0},
    "graveyard": {"wood": 14, "stone": 3, "build_time": 10.0},
}
CONSTRUCTION_SITE_SIZE = {
    "campfire": (36, 36),
    "storage": (46, 46),
    "graveyard": (60, 44),
}
CONSTRUCTION_SITE_COLOR_INCOMPLETE = (220, 40, 40)
CONSTRUCTION_SITE_COLOR_READY = (235, 140, 30)
CONSTRUCTION_SITE_BORDER_THICKNESS = 3

# ---------- Эффекты биомов на существо ----------
DESERT_THIRST_DRAIN_MULTIPLIER = 1.4
DESERT_ENERGY_DRAIN_MULTIPLIER = 1.25
DESERT_CALMNESS_PENALTY_PER_SEC = 0.4
RIVER_SWIM_SPEED_MULTIPLIER = 0.5

# ---------- Психика ----------
PSYCHE_STAT_MIN = -100.0
PSYCHE_STAT_MAX = 100.0
PSYCHE_DECAY_RATE = 0.06

PSYCHE_PET_BONUS = 8.0
PSYCHE_HIT_PENALTY = -18.0
PSYCHE_GRAB_GOOD_BONUS = 5.0
PSYCHE_GRAB_BAD_PENALTY = -8.0

PSYCHE_TALK_JOY_RATE = 0.35
PSYCHE_TALK_ATTACHMENT_RATE = 0.15
PSYCHE_QUARREL_PENALTY = -6.0
PSYCHE_HELP_GIVER_BONUS = 4.0
PSYCHE_HELP_RECEIVER_BONUS = 7.0

PSYCHE_PAIR_BONUS = 15.0
PSYCHE_PARTNER_LOSS_PENALTY = -35.0

PSYCHE_TERRITORY_INTRUDER_PENALTY = -10.0
PSYCHE_TERRITORY_OWNER_BONUS = 3.0
PSYCHE_HAZARD_PENALTY = -9.0
PSYCHE_BIRTH_BONUS = 12.0

PSYCHE_CURIOSITY_INFLUENCE = 0.35
PSYCHE_FREEZE_INFLUENCE = 0.35
PSYCHE_QUARREL_INFLUENCE = 0.5
PSYCHE_ATTACHMENT_PAIR_INFLUENCE = 12.0

PSYCHE_SPEED_INFLUENCE = 0.12
PSYCHE_TERRITORY_BOLDNESS_INFLUENCE = 0.5
PSYCHE_EMPATHY_THRESHOLD_INFLUENCE = 20.0
PSYCHE_HELPFULNESS_INFLUENCE = 0.6
PSYCHE_SOCIAL_RESPONSE_INFLUENCE = 0.5
PSYCHE_JEALOUSY_INFLUENCE = 0.4

# ---------- Ролевая метка для UI ----------
RELATIONSHIP_SCROLL_SPEED = 25

# ---------- Древо Родословной ----------
GENEALOGY_MAX_DEPTH = 6
GENEALOGY_NODE_RADIUS = 16
GENEALOGY_ROW_HEIGHT = 130
GENEALOGY_SLOT_WIDTH = 90
GENEALOGY_PARTNER_OFFSET = 70
GENEALOGY_LINE_COLOR = (150, 150, 150)
GENEALOGY_PARTNER_LINE_COLOR = (230, 100, 180)
GENEALOGY_ROOT_RING_COLOR = (255, 210, 60)
GENEALOGY_CROSS_COLOR = (200, 60, 60)
GENEALOGY_PANEL_WIDTH = 900
GENEALOGY_PANEL_HEIGHT = 640