"""Настройки, специфичные для волков."""

# ---------- Базовые характеристики (хищник: быстрее и зорче овец/коров) ----------
WOLF_HP_MAX = 70
WOLF_HUNGER_MAX = 22
WOLF_THIRST_MAX = 20
WOLF_ENERGY_MAX = 90
WOLF_VISION_RADIUS = 600
WOLF_SPEED = 110
WOLF_BASE_SPEED_MULTIPLIER = 1.0
WOLF_RADIUS = 13

# ---------- Шкура ----------
HIDE_LIFETIME = 45.0
HIDE_SIZE = 18
HIDE_COLOR = (200, 200, 205)
HIDE_COLOR_BORDER = (150, 150, 155)
WOLF_HIDE_MIN, WOLF_HIDE_MAX = 5, 9

# ---------- Внешний вид: светло-серый прямоугольник + 2 маленькие треугольные ножки того же цвета ----------
WOLF_BODY_WIDTH = 30
WOLF_BODY_HEIGHT = 16
WOLF_COLOR_BODY = (190, 190, 195)
WOLF_COLOR_BODY_BORDER = (140, 140, 145)
WOLF_COLOR_LEG = WOLF_COLOR_BODY
WOLF_LEG_WIDTH = 8
WOLF_LEG_HEIGHT = 8

# ---------- Текст ----------
WOLF_KIND_NAME = "Волк"
WOLF_INFO_HIDE = "Шкура: {count}"

# ---------- ИИ: бродяжничество, охота, водопой, поедание мяса ----------
WOLF_HUNGER_DRAIN_INTERVAL = 35.0
WOLF_THIRST_DRAIN_INTERVAL = 18.0
WOLF_ENERGY_DRAIN_INTERVAL_HUNT = 8.0
WOLF_ENERGY_REGEN_INTERVAL = 12.0
WOLF_STARVE_HP_DRAIN = 1.5
WOLF_DEHYDRATE_HP_DRAIN = 3.0

WOLF_WANDER_DISTANCE = (80, 200)
WOLF_WANDER_TIMER = (2.5, 5.0)
WOLF_DRINK_DISTANCE = 34
WOLF_DRINK_RATE = 2.5
WOLF_THIRST_SEEK_RATIO = 0.6

WOLF_HUNT_HUNGER_RATIO = 0.5
WOLF_CHASE_SPEED_MULTIPLIER = 1.4
WOLF_BITE_DISTANCE = 22
WOLF_BITE_DAMAGE = 9
WOLF_BITE_COOLDOWN = 1.2
WOLF_EAT_DISTANCE = 20
WOLF_EAT_RATE = 1.5