"""Настройки, специфичные для коров."""

# ---------- Базовые характеристики ----------
COW_HP_MAX = 90
COW_HUNGER_MAX = 28
COW_THIRST_MAX = 28
COW_ENERGY_MAX = 100
COW_VISION_RADIUS = 450
COW_SPEED = 60
COW_BASE_SPEED_MULTIPLIER = 1.0
COW_RADIUS = 16

# ---------- Ресурсы ----------
COW_MEAT_MIN, COW_MEAT_MAX = 20, 32
COW_MILK_MAX_CHARGES = 4
# ---------- Кожа (выпадает после смерти) ----------
COW_LEATHER_MIN, COW_LEATHER_MAX = 6, 10
LEATHER_LIFETIME = 45.0
LEATHER_SIZE = 20
LEATHER_COLOR = (120, 80, 45)
LEATHER_COLOR_BORDER = (80, 50, 25)

# ---------- Внешний вид: тёмно-серый прямоугольник + белые точки + 2 тонкие ножки того же цвета ----------
COW_BODY_WIDTH = 44
COW_BODY_HEIGHT = 26
COW_COLOR_BODY = (70, 70, 78)
COW_COLOR_BODY_BORDER = (40, 40, 46)
COW_COLOR_SPOTS = (235, 235, 235)
COW_SPOT_COUNT_RANGE = (3, 5)
COW_SPOT_RADIUS = 3
COW_COLOR_LEG = COW_COLOR_BODY
COW_LEG_WIDTH = 4
COW_LEG_HEIGHT = 12

# ---------- Текст ----------
COW_KIND_NAME = "Корова"
COW_INFO_LEATHER = "Кожа: {count}"

# ---------- ИИ: бродяжничество, выпас, водопой, паника при волках ----------
COW_HUNGER_DRAIN_INTERVAL = 45.0
COW_THIRST_DRAIN_INTERVAL = 20.0
COW_ENERGY_DRAIN_INTERVAL_FLEE = 6.0
COW_ENERGY_REGEN_INTERVAL = 10.0
COW_STARVE_HP_DRAIN = 1.5
COW_DEHYDRATE_HP_DRAIN = 3.0

COW_WANDER_DISTANCE = (60, 160)
COW_WANDER_TIMER = (3.0, 6.0)
COW_GRAZE_DISTANCE = 20
COW_GRAZE_RATE = 1.2
COW_DRINK_DISTANCE = 34
COW_DRINK_RATE = 2.5
COW_HUNGER_SEEK_RATIO = 0.6
COW_THIRST_SEEK_RATIO = 0.6
COW_HUNGER_SATISFY_RATIO = 0.85
COW_THIRST_SATISFY_RATIO = 0.85
COW_FLEE_RUN_DISTANCE = 160
COW_FLEE_SPEED_MULTIPLIER = 1.5